org.elysium.test/src/org/elysium/test/integration/Integration.java
If an integration test fails, it would be nice to see the errors not only in the console. With this simple modification the problematic file appears as error message on the failing test in the JUnit-View.
In the first place, this pull request is a test run (for me) for potential further contributions.
=> failing integration test shows file path as error message

org.elysium.ui/src/org/elysium/ui/compiler/CompilerConsole.java, org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java
I added a button for cancelling a compilation job, and for closing the compiler console for a particular file.
If the console is not pinned, the console for a particular file is activated if its content changes (otherwise a finished job may remain in the foreground even if other builds are still running).
=> #48 add cancel button to compile view

org.elysium.ui/src/org/elysium/ui/contentassist/LilyPondProposalProvider.java
There was unnecessary code in the proposal provider. Most of the converting and all of the applying changes is already done by the framework. This simplified version seems to work even better as it does not leave out the trailing quotes, so after applying the proposal, the result is valid.
=> simplify proposal provider

org.elysium.ui/src/org/elysium/ui/compiler/CompilerConsole.java
Unfortunately, I introduced an NPE with a previous fix. It hits e.g. on Eclipse startup or if the console was not active and hence the CompilerConsole is not initialized yet.
=> fix NPE in CompilerConsole

org.elysium.ui/src/org/elysium/ui/refactoring/MoveFileParticipant.java, org.elysium.ui/src/org/elysium/ui/refactoring/RefactoringSupport.java, org.elysium.ui/src/org/elysium/ui/refactoring/RenameFileParticipant.java
There are a number of stumble stones connected with the refactoring.
* a MoveResourceChange must be created only if the corresponding file is not part of the refactoring anyway (user selection of multiple files for moving)
* a MoveResourceChange/DeleteResourceChange does not trigger a new refactoring - i.e. another RefactoringParticipant responsible for that change will not be notified (hence the dirty hack in ensureScoreCanBeRefactored making sure that the Score View's delete participant unregisters the score; I have not found cleaner solution)
Moving the pdf alone does not work, yet. For that a MoveParticipant in the pdf view plugin would be the way to go.
=> #72 allow moving source along with compiled score

Elysium.setup
I did not rewrite the entire setup, as the compare view indicates.
I extracted update site urls to variables, added XtextTools and added Juno, Kepler and Mars as additional possible target platforms - changes proposed in #74
=> add XtextTools and more possible target platforms to Oomph setup

org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java, org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java, org.elysium.ui/src/org/elysium/ui/compiler/NumberedQueueSchedulingRule.java, org.elysium.ui/src/org/elysium/ui/compiler/preferences/CompilerPreferenceConstants.java, org.elysium.ui/src/org/elysium/ui/compiler/preferences/CompilerPreferenceInitializer.java, org.elysium.ui/src/org/elysium/ui/compiler/preferences/CompilerPreferencePage.java
On my machine a clean build of a project with many files freezes the system because many LilyPond instances are running simultaneously. I propose that the user can configure the number of parallel executions (on the already existing compiler preference page).
The implementation makes use of scheduling rules preventing multiple jobs with the same rule running at the same time.
=> restrict number of parallel running LilyPond instances

org.elysium.test/src/org/elysium/test/integration/Integration.java, org.elysium.test/src/org/elysium/test/regression/GrammarRegressions.xtend, org.elysium.ui/src/org/elysium/ui/labeling/LilyPondLabelProvider.java, org.elysium/src/org/elysium/LilyPond.xtext, org.elysium/src/org/elysium/LilyPondRuntimeModule.java, org.elysium/src/org/elysium/formatting/LilyPondFormatter.java, org.elysium/src/org/elysium/resource/LilyPondResourceDescriptionStrategy.java, org.elysium/src/org/elysium/scoping/LilyPondScopeProvider.java, org.elysium/src/org/elysium/scoping/LilyPondSimpleLocalScopeProvider.java
I have made changes to the indexing and scoping, in particular eliminating the PropertyAssignment (for some reason it was impossible to give both assignment types a common super type - all attempts lead to compile errors in the generated code).
SchemeIdentifier-like names seem to be valid for assignmnets - at least LilyPond accepted
my-UpBow = \upbow
If there are restrictions in that direction, it is much easier to deal with them in the validator than in the grammar.
Please comment on the modifications in the LilyPondResourceDescriptionStrategy. I could not find a reason to put all elements in the index. Click and point worked with the simplified version as well. This way the index is much smaller and much faster to build (improved performance for the integrationtests).
=> more passing integration tests

org.elysium.test/src/org/elysium/test/regression/GrammarRegressions.xtend, org.elysium/src/org/elysium/LilyPond.xtext
simple scheme defines referrable as assignments, allowing two more integration test cases to pass
I am not sure what name and value may look like, so the SimpleSchemeAssignment rule may still be refined
=> add simple scheme define (aliases)

org.elysium.test/src/org/elysium/test/regression/GrammarRegressions.xtend, org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondHyperlinkHelper.java, org.elysium/src/org/elysium/importuri/LilyPondImportUriResolver.java
I restricted resolving the URI differently to Windows. On my Mac URI.create("1 foo.ly") does not throw an exception. On my Windows machine, it does.
=> fix #96 - problems with include filenames containing space

org.elysium.ui/src/org/elysium/ui/compiler/CancellableProcessUtils.java, org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java, org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java
This is a proposed fix for #95. The compile job for .ily files still has to be created in order to remove old markers but I removed all steps I thought to be unnecessary within the job. I sorted the files for compilation so that fast jobs (.ily) are handled first. This keeps the list of open jobs short (progress view).
Previously a new resource set was used for each direct include calculation. Changing that to one common resource set for each build speeds up the process. For the same reason I introduced the set of files for which this calculation has been done already (the filesToBuild-set does not quite serve the same purpose, it does not prevent duplicate calculation). As a result (on my slow Windows machine), the time for calculating allIncludingFiles dropped from 45 seconds to 4 …
=> exclude .ily from comlpete compilation and speed up build process

org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java
Dialog is opened only once. Of course, if the user chooses not to modify the path or configures it incorrectly again, the dialog is opened again.
A potential modification would be to leave the state of the variable "true" in case the user answers "no". In this case the dialog would not reopen again during this eclipse session.
=> #109 open question for configuring LilyPond executable path only once

Elysium.setup
The optional api tools requirement is useful for the "export deployable" feature.
The eclipse ini parameter does not hurt in case you want to test elysium in the development eclipse (dropins folder).
=> enhance oomph setup (api tools and eclipse ini)

org.elysium/src/org/elysium/GenerateLilyPond.mwe2.launch
The setup task fails if the default Xmx settings do not provide enough memory - explicitly set the value in the launch config.
=> add Xmx parameter to workflow launch config

org.elysium.parent/org.elysium.tests/src/org/elysium/tests/importuri/ImportUriResolverTest.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/preferences/LilyPondValidatorConfigBlock.java, org.elysium.parent/org.elysium/src/org/elysium/conversion/LilyPondStringValueConverter.java, org.elysium.parent/org.elysium/src/org/elysium/conversion/LilyPondValueConverterService.java, org.elysium.parent/org.elysium/src/org/elysium/importuri/LilyPondImportUriResolver.java, org.elysium.parent/org.elysium/src/org/elysium/scoping/LilyPondImportUriGlobalScopeProvider.java, org.elysium.parent/org.elysium/src/org/elysium/validation/IssueCodes.java, org.elysium.parent/org.elysium/src/org/elysium/validation/LilyPondValidator.java
This PR addresses #133 warning about absolute includes, #124 removing the info level from linking problems (possibly causing an IllegalStateException) and #125 preventing exceptions when including a directory or file with unkown file extensions.
It is not a refactoring of the include mechanism itself, but a first step to a stable behaviour.
=> Validation preference

Elysium.setup, org.elysium.parent/org.elysium.ui.tests/src/org/elysium/ui/contentassist/LilyPondProposalProviderTest.xtend, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/contentassist/LilyPondProposalProvider.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/contentassist/MidiInstruments.java
This is a very simple code completion for the midi instruments listed at http://lilypond.org/doc/v2.19/Documentation/notation/midi-instruments
It fires within the quotation marks in an assignment like `\set midiInstrument =#"violin"`
=> code completion for midi instruments

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/updater/SyntaxUpdaterProcessBuilderFactory.java, org.elysium.parent/org.elysium/src/org/elysium/LilyPondConstants.java, org.elysium.parent/org.elysium/src/org/elysium/importuri/LilyPondImportUriResolver.java
This PR addresses #128. The invocation of the converter needs to be done differently on windows, where .py files may not necessarily be treated as executable. The implemented way looks for a python-executable next to the LilyPond executable. If python did not come with LilyPond it is expected to be on the path. (A more elaborate version would ask for the python executable path).
With your permission, I would add two further modifications to this PR.
* I would invoke the syntax update only if Lilypond compilation is activated as well. To me it makes no sense to continuously run the syntax updater when editing and saving, if I don't want to compile as well.
* I would like to remove the redundant --edit parameter from SyntaxUpdaterProcessBuilderFactory.get, this parameter is set in …
=> Syntax updater

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/updater/SyntaxUpdaterProcessBuilderFactory.java
With your additional commit (after PR #145), you removed the duplicate edit parameter from CompilerJob. I'd remove it completely from SyntaxUpdaterProcessBuilderFactory, because there it is set only if no editor is open. However, the compiler closes the editor, anyway. So now, the editor would be closed and reopened even though the edit parameter is not set at all.
Also, I suggest invoking the syntax update only if compilation is active (see comment 1 in #145)
=> update syntax only when compile is active

org.elysium.parent/org.elysium.tests/src/org/elysium/tests/importuri/ImportUriResolverTest.java, org.elysium.parent/org.elysium.tests/src/org/elysium/tests/regression/GrammarRegressions.xtend, org.elysium.parent/org.elysium.ui/plugin.xml, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/Activator.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondUiModule.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/handlers/RecompileEditedHandler.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/handlers/RecompileSelectedHandler.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/handlers/RecompileViewedHandler.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/outdated/OutdatedMarkerAdder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondHyperlinkHelper.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondLanguageSpecificURIEditorOpener.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondResourceForIEditorInputFactory.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/refactoring/LilyPondRefactoringInjects.java, org.elysium.parent/org.elysium/src/org/elysium/importuri/LilyPondImportUriResolver.java, org.elysium.parent/org.elysium/src/org/elysium/importuri/LilyPondResolvedUri.java, org.elysium.parent/org.elysium/src/org/elysium/validation/LilyPondValidator.java
This PR addresses #132 (and #146). When resolving includes, as far as possible the real file location is used as base for resolving the include. Within a running eclipse this should always work. More problematic are unit tests where no platform is running and URIs are synthetic.
LilyPondImportUriResolver no longer tries to resolve to a platform URI (i.e. a file located in the workspace) but rather to the absolute file location of the included file. The LilyPondLanguageSpecificURIEditorOpener tries to find a workspace version for such an absolute location and opens that if present - however with the absolute file URI for the openeed file (so find references works #146), otherwise a read-only version is opened as before.
The advantage of this approach should be that import resolution should …
=> rewrite include resolution

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/outdated/OutdatedMarkerAdder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/markers/MarkerTypes.java
The PR addresses #148. The main modifications are that outdated-markers are removed only by the LilyPond compiler and that they are removed only if actual compilation took place.
Only if the compiler was really invoked can we be sure that the output is up to date. The UP_TO_DATE-marker logic seems obsolete.
I experimented with a modified recompile hash for indicating that a recompile is necessary - using a normalized text representation without hidden nodes (i.e. without white spaces or comments). The idea is, that the output will be the same if comments are added, spaces, i.e. no structural changes have taken place. The problem is that with those modifications the score hyperlinks are still affected. So if click-to-point generation is disabled the modified hash is OK, if it is enabled …
=> marker logic

org.elysium.parent/org.elysium.tests/src/org/elysium/tests/Validator.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerProcessBuilderFactory.java, org.elysium.parent/org.elysium/src/org/elysium/validation/LilyPondValidator.java
I have added the compile option.
The second commit is a naive validation implementation - the semantic structure for schemes is too complex to do it in a nice way...
=> #154 add default compiler option for relative includes

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondXtextEditor.java
This PR ensures that workspace external files are opened read only. As a consequence https://github.com/thSoft/eclipse-commons/pull/43 will not cause problems.
=> always open workspace external files read only

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondUiModule.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondTargetUriCollector.java
Finding references within an opened file was broken. This is because the link target points to the file URI (absolute location), but the file is opened with platform URI. This fix adds a platform search target, if the file URI points to a workspace file.
This resolves #146.
=> #146 fix find references within local file

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondUiModule.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondXtextDocumentProvider.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondXtextEditor.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondLanguageSpecificURIEditorOpener.java
This is an alternative (and superior) approach to opening workspace external files read only. Currently, the editor input is wrapped as XtextReadonlyEditorInput. For score to source links this caused each link to be opened in a new editor.
The fix is extending XtextDocumentProvider which was responsible for enabling editing for orignially read-only inputs. In addition, the editor's title tooltip now shows name and location, so you can easily see where the opened file is located.
=> alternative OpenReadOnly

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondXtextEditor.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondAutoBuildWarning.java
With this PR, a notification is shown if automatic build is disabled, on first opening a LilyPond file. It is shown once after automatic build has been turned off.
=> #171 add warning for deactivated auto build

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CancellableProcessUtils.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerProcessBuilderFactory.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/problems/ProblemParser.java
This PR tries to improve LilyPond compile error parsing. The error stream is redirected (see java doc) so that messages will not get lost, even if errors were somehow globally redirected to the regular output. The second change is adding the encoding to the locale - otherwise the output remained English even though the locale was German.
Testet on a Windows and a Linux system, to be confirmed on Mac.
These two commits should not be problematc. I still think that the Problem parser should not depend on the locale directly. As seen by #178, even though the locale may be set, LilyPond could use a different language. This language should be inferred directly from the console output.
=> Problem parsing minimal

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/version/LilyPondVersion.java
There was a TODO in LilyPondVersion which is addressed by this PR. The installed LilyPond is run for determining the version (once). In case of a problem, a fallback is used.
=> use LilyPond for obtaining version

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerProcessBuilderFactory.java
If a compile action is invoked on a linked file, currently the compiler cannot find it. This is because the IFile's parent (actual workspace project) may not be the phyiscal parent of the file. Changing the order - getting the location (path) and then removing the last segment - fixes this problem.
However, the linked file support is not perfect, even then. Show in score/audio might well fail because the compiled files are not automatically linked. Replacing the file extension of the source file leads to an IFile which is unknown to Eclipse.
I guess, linked files are hardly used, so even the bug fix of this PR could be ignored...
=> fix compilation of linked files

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerOutputProcessor.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/problems/LilyPondWorkspaceExternalHyperlink.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/problems/ProblemHyperlinkAdder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/problems/ProblemParser.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/hyperlinks/LilyPondTargetUriCollector.java
This PR implements the language fallback discussed in #178. Mostly, it is refactoring splitting up of the previously static parse method. There is a second reason for introducing state to the problem parser. Determining the file with the issue will have to be adapted. The current implementation can easily fail for more complex include constallations.
Checking the path against the include information present in the index may help improve finding the file to mark.
=> #178 add problem parse language fallback

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/audio/AudioViewType.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/score/ScoreViewType.java
Currently, if score view/audio view are open and "linked" with the selected file, changing selection to a file that may not have a corresponding compiled file shows the "pdf/midi file does not exists" warning.
Generally, I like the link with editor functionality, but it is irritating if you jump from the score to an ily-file and the score disappears. The selection change listener in FileView is not null safe, so what I do is returning a file with a dummy extension in case the selected file cannot be the source file of a potential pdf/midi file.
=> link file view only if compiled file may exist

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/LilyPondPerspective.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/refactoring/LilyPondRefactoring.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/refactoring/LilyPondRefactoringDelegate.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/refactoring/LilyPondSourceFileRefactoring.java
This PR addresses #106. When compilation is invoked and involves open dirty files, the user is asked whether to continue (ignoring the unsaved changes). Aborting the compilation allows the user to create a clean state and then invoke compilation again.
Refactorings are completely prevented if an open dirty file is involved.
=> Compile dirty

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/autoedit/LilyPondAutoEditStrategyProvider.java
This PR addresses #25. Auto edit for multi line comments failed because the strategy was not registered for the single line comment partition, but if the prefix is `%` this will be the current partition.
This current fix also involves *not* registering regular braces `{}` for the comment partition. This is because braces and multiline comment strategy will fire simultaneously leading to strange results when pressing enter between `%{` and `%}`. This is the simplest solution. Of course auto edit for braces will now not work when in a comment or multi line comment, which I consider acceptable.
Otherwise we would have to sub class the strategy and apply it for braces only if there was no percent befor the brace.
=> #25 fix multi line comment auto edit

org.elysium.parent/org.elysium.ui/plugin.xml, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/handlers/RecompileSelectedHandler.java
As recompilation is not possible on an ily file anymore, it may be less easy to invoke recompilation on all including files (which may be spread over different folders), especially if compile on save is deactivated.
This pull request introduces a preference value controlling whether all files or only those marked as outdated will be processed, when recompilation is invoked on a folder or a project.
(My hope was that this makes #127 obsolete, as the Elysium's compiler preference page is completely different from the standard Xtext preference page and hence allowing project specific settings may not be easy. However, the use case there - compile on save in one project but not another - remains)
=> recompile only outdated when container is selected

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java
Instantiate new set of files to compile. We cannot be sure that the
parameter set is modifiable.
=> #192 fix Recompile UnsupportedOperationException

org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerJob.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondBuilder.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/LilyPondFilesToCompile.java, org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/RefreshProjectJob.java, org.elysium.parent/org.elysium/src/org/elysium/resource/LilyPondResourceDescriptionStrategy.java, org.elysium.parent/org.elysium/src/org/elysium/scoping/LilyPondImportUriGlobalScopeProvider.java
Remove markers in included files as well, not only in the main file to
be compiled.
If you merge PR #192 first, I'd rebase this commit.
=> #194 improve marker cleanup
